#!/bin/sh
# bwlch - file manager experiment

while true ; do
	file="$(ls -Fa | arzhur)"

	if [ "$file" = ":" ]; then # enter command mode
		"$(arzhur -n)"
	elif [ -d "$file" ]; then
		cd "$file" # move into directories
	elif [ -f "$file" ]; then
		"$(arzhur -n)" "$file" # run a supplied command with the selected file as an argument
	fi
done
